import Link from 'next/link';
import { notFound } from 'next/navigation';
import { Card, PageHeader, StatusBadge } from '@propertyos/ui';
import type { StatusTone } from '@propertyos/ui';
import { readAs, requireOperator } from '@/lib/auth';
import { formatDate } from '@/lib/format';
import { loadDocument } from '@/lib/operations-queries';

export const metadata = { title: 'Document' };
export const dynamic = 'force-dynamic';

const SCAN: Record<string, { tone: StatusTone; label: string; glyph: string }> = {
  pending:                { tone: 'caution',  label: 'Awaiting scan', glyph: '◐' },
  skipped_not_configured: { tone: 'caution',  label: 'Not scanned',   glyph: '▲' },
  clean:                  { tone: 'positive', label: 'Clean',         glyph: '✓' },
  infected:               { tone: 'critical', label: 'Flagged',       glyph: '✕' },
  failed:                 { tone: 'critical', label: 'Scan failed',   glyph: '✕' },
  system_generated:       { tone: 'info',     label: 'Generated by PropertyOS', glyph: '◆' },
};

function formatBytes(bytes: string): string {
  const value = Number(bytes);
  if (value < 1024) return `${value} B`;
  if (value < 1024 * 1024) return `${(value / 1024).toFixed(0)} KB`;
  return `${(value / (1024 * 1024)).toFixed(1)} MB`;
}

/**
 * One document, with the generated ones readable on the page.
 *
 * Both the lease screen and the agreement list linked here and nothing was
 * listening: the document a landlord had just generated could only be
 * downloaded, from a different screen, by title. An agreement you cannot read
 * before sending is an agreement you send unread.
 *
 * Only a PDF PropertyOS itself rendered is shown inline, and the rule that
 * decides so lives in the domain, not here. Anything a person uploaded is
 * offered as a download, because rendering someone else's file inside this
 * origin is a different kind of risk and the declared content type is their
 * claim, not a fact.
 */
export default async function DocumentPage({
  params,
}: {
  params: Promise<{ org: string; documentId: string }>;
}) {
  const { org, documentId } = await params;
  const context = await requireOperator(org);
  const document = await readAs(context.viewer, (tx) =>
    loadDocument(tx, context.organisationId, documentId),
  );
  // RLS already decided what this operator can see, so a miss here is a miss:
  // not visible and not existing look the same, deliberately.
  if (!document) notFound();

  const scan = SCAN[document.scan_status] ?? SCAN.pending!;
  const previewable =
    document.scan_status === 'system_generated' && document.content_type === 'application/pdf';
  const backHref = document.lease_id
    ? `/app/${org}/leases/${document.lease_id}`
    : `/app/${org}/documents`;

  return (
    <div className="space-y-6">
      <Link href={backHref} className="text-sm text-spike-600 hover:underline">
        ← {document.lease_id ? 'Back to the lease' : 'All documents'}
      </Link>

      <PageHeader
        title={document.title}
        description={`${document.classification.replace(/_/g, ' ')} · ${
          formatBytes(document.byte_size)} · added ${
          formatDate(document.uploaded_at, context.timeZone)}${
          document.uploader ? ` by ${document.uploader}` : ''}`}
        actions={
          document.quarantined ? undefined : (
            <a
              href={`/app/${org}/documents/${documentId}/download`}
              className="rounded-lg bg-spike-500 px-3.5 py-2 text-sm font-medium text-white"
            >
              Download
            </a>
          )
        }
      />

      <div className="flex flex-wrap items-center gap-2">
        <StatusBadge tone={scan.tone} glyph={scan.glyph}>{scan.label}</StatusBadge>
        {document.visibility === 'resident_shared' ? (
          <StatusBadge tone="info">Shared with the resident</StatusBadge>
        ) : (
          <StatusBadge tone="neutral">Internal only</StatusBadge>
        )}
        {document.superseded ? <StatusBadge tone="neutral">Replaced by a later issue</StatusBadge> : null}
        {document.lease_reference ? (
          <span className="text-sm text-ink-500">Lease {document.lease_reference}</span>
        ) : null}
        {document.property_name ? (
          <span className="text-sm text-ink-500">{document.property_name}</span>
        ) : null}
      </div>

      {document.quarantined ? (
        <Card className="border-caution-700/25 bg-caution-50 p-4">
          <p className="text-sm font-semibold text-caution-700">This file is quarantined</p>
          {/* Which of the two it is matters to the reader: one is a thing to go
              and configure, the other a thing that went wrong. Saying "no
              scanner is configured" about a scan that ran and failed would send
              someone to the wrong runbook. */}
          <p className="mt-1 text-sm text-ink-700">
            {document.scan_status === 'skipped_not_configured'
              ? 'No malware scanner is configured, so it has NOT been scanned.'
              : document.scan_status === 'infected'
                ? 'A scanner flagged this file.'
                : 'The scan did not complete, so the file has NOT been cleared.'}{' '}
            It cannot be read here, downloaded or shared. That is enforced by the database, not
            only by this screen.
          </p>
          {document.scan_detail ? (
            <p className="mt-2 text-xs text-ink-500">{document.scan_detail}</p>
          ) : null}
        </Card>
      ) : previewable ? (
        <Card className="overflow-hidden p-0">
          {/* An object rather than an iframe: a browser with no PDF viewer falls
              back to the children instead of showing an empty frame. */}
          <object
            data={`/app/${org}/documents/${documentId}/preview`}
            type="application/pdf"
            aria-label={`${document.title}, PDF`}
            className="h-[80vh] w-full"
          >
            <div className="p-5 text-sm text-ink-700">
              Your browser will not display a PDF on the page.{' '}
              <a
                href={`/app/${org}/documents/${documentId}/download`}
                className="font-medium text-spike-600 hover:underline"
              >
                Download it instead
              </a>
              .
            </div>
          </object>
        </Card>
      ) : (
        <Card className="p-5">
          <p className="text-sm text-ink-700">
            This file was uploaded rather than generated by PropertyOS, so it is not shown on
            the page. Download it to open it in the application it belongs to.
          </p>
          <p className="mt-2 text-xs text-ink-500">
            Every download is authorised per request and recorded against your name.
          </p>
        </Card>
      )}
    </div>
  );
}
